name: Release & Packagist

on:
  push:
    tags:
      - "v*"


permissions:
  contents: write

jobs:
  release-packagist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate composer.json
        run: composer validate --strict

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true

      - name: Notify Packagist
        env:
          PACKAGIST_USERNAME: ${{ secrets.PACKAGIST_USERNAME }}
          PACKAGIST_TOKEN: ${{ secrets.PACKAGIST_TOKEN }}
        run: |
          PAYLOAD=$(printf '{"repository":{"url":"https://github.com/%s"}}' "$GITHUB_REPOSITORY")
          curl -sSf -X POST \
            -H 'Content-Type: application/json' \
            -d "$PAYLOAD" \
            "https://packagist.org/api/update-package?username=${PACKAGIST_USERNAME}&apiToken=${PACKAGIST_TOKEN}"
